
default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5

development:
 <<: *default
 database: maestro_dev
 
test:
 <<: *default
 database: maestro_test

production:
 <<: *default
 database: maestro


